-- MySQL Script generated by MySQL Workbench
-- 03/29/16 14:52:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `new_schema` ;

-- -----------------------------------------------------
-- Table `new_schema`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema`.`EMPRESA` (
  `idEMPRESA` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `inscricaoEstadual` VARCHAR(20) NOT NULL,
  `razaoSocial` VARCHAR(50) NOT NULL,
  `tipoLogradouro` INT NOT NULL,
  `logradouro` VARCHAR(50) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(50) NULL,
  `bairro` VARCHAR(30) NOT NULL,
  `referencia` VARCHAR(50) NULL,
  `cidade` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `email` VARCHAR(50) NULL,
  `tributacao` INT NOT NULL,
  `atividade` INT NOT NULL,
  `inscricaoMunicipal` VARCHAR(14) NULL,
  `rntrc` VARCHAR(30) NOT NULL,
  `inscricaoSuframa` VARCHAR(9) NULL,
  `cotm` VARCHAR(20) NULL,
  `idMatriz` INT NULL,
  PRIMARY KEY (`idEMPRESA`),
  CONSTRAINT `FK_EMPRESA_MATRIZ`
    FOREIGN KEY (`idMatriz`)
    REFERENCES `new_schema`.`EMPRESA` (`idEMPRESA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `index2` ON `new_schema`.`EMPRESA` (`cnpj` ASC);

SHOW WARNINGS;
CREATE INDEX `index3` ON `new_schema`.`EMPRESA` (`razaoSocial` ASC);

SHOW WARNINGS;
CREATE INDEX `fk__idx` ON `new_schema`.`EMPRESA` (`idMatriz` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
